// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCimMMoSin9tZ1xmgHB2iNDag_WEjPNBSM',
    appId: '1:1086586787363:web:f390ca72f5d5b309620396',
    messagingSenderId: '1086586787363',
    projectId: 'ditonton-9b469',
    authDomain: 'ditonton-9b469.firebaseapp.com',
    storageBucket: 'ditonton-9b469.appspot.com',
    measurementId: 'G-H72HKTCSBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoWEAONdL4VgSkeRPXw2vkJZks6o82v1Q',
    appId: '1:1086586787363:android:72a0f883a561fffc620396',
    messagingSenderId: '1086586787363',
    projectId: 'ditonton-9b469',
    storageBucket: 'ditonton-9b469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYbHsZj8nonx_U_jZn7NqXXnrpqeHzlo',
    appId: '1:1086586787363:ios:c2583c1977ebd5b2620396',
    messagingSenderId: '1086586787363',
    projectId: 'ditonton-9b469',
    storageBucket: 'ditonton-9b469.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
